import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ToastifyContainer } from "../components/ToastifyContainer";
import Nav from "../components/Nav";
import Menu from "../components/Menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ApplicationLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen flex flex-col bg-[#C5C5C5]">
      <Nav />
      <div className="flex flex-1">
        <Menu />

        <main className="flex-1">{children}</main>
      </div>
    </div>
  );
}
